---
# -- Static resources ----------------------------------------------------------
resources:
  jetpants-search:
    css: http://cdn.jetpants.com/css/jetpants-search-201005021531.css
    js: http://cdn.jetpants.com/js/jetpants-search-201005071731.js

# -- Providers -----------------------------------------------------------------
providers:
  boss: &boss
    enabled: true
    url: http://boss.yahooapis.com/ysearch
    version: v1

  images:
    <<: *boss
    enabled: false

  twitter:
    enabled: true
    url: http://search.twitter.com/search.json

  web:
    <<: *boss
    timeout: 2000
